<a href="https://colab.research.google.com/github/theatu824/MSSP607-GitHub/blob/main/WeeklyModules/Week06/PARTICIPATION_ACTIVITY_Week_6_Write_a_lamda_function_for_a_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools
pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)
from google.colab import userdata
import os
Git_Key = userdata.get('Git_Key')
owner = 'theatu824' # Replace with the GitHub repository owner
repository = 'MSSP607-GitHub' # Replace with the GitHub repository name
clone_url = f'https://{Git_Key}@github.com/{owner}/{repository}.git'
# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])
# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP607-GitHub/MSSP607-GitHub/MSSP607-GitHub

In [ ]:
# Use Google Colabs and Python to write a lambda function that takes the Student Performance Data Set found here and returns another data frame.
df = pd.read_csv("data/Student Performance Data.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [ ]:
#Data Cleaning
df["math score"].isna().sum()

np.int64(0)

In [ ]:
below_60 = lambda df: df[df["math score"] < 60]
filtered_df = below_60(df)
filtered_df

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
7,male,group B,some college,free/reduced,40,43,39,122,none,low
9,female,group B,high school,free/reduced,38,60,50,148,none,low
10,male,group C,associate's degree,standard,58,54,52,164,none,medium
11,male,group D,associate's degree,standard,40,52,43,135,none,low
...,...,...,...,...,...,...,...,...,...,...
985,male,group A,high school,standard,57,51,54,162,none,medium
986,female,group C,associate's degree,standard,40,59,51,150,none,low
988,female,group A,some high school,free/reduced,44,45,45,134,none,low
992,female,group D,associate's degree,free/reduced,55,76,76,207,none,medium
997,female,group C,high school,free/reduced,59,71,65,195,completed,medium

In [ ]:
check_list = filtered_df["math score"].unique().tolist()
print(sorted(check_list))

[0, 8, 18, 19, 22, 23, 24, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]