<a href="https://colab.research.google.com/github/theatu824/MSSP607-GitHub/blob/main/WeeklyModules/Week05/PARTICIPATION_ACTIVITY_Week_5_Merge_two_Pandas_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools
pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

from google.colab import userdata
import os
import subprocess

github_token = userdata.get('Git_Key') #Retrieve secret key for user
owner = 'theatu824' # Replace with the GitHub repository owner
repository = 'MSSP607-GitHub' # Replace with the GitHub repository name

clone_url = f'https://x-access-token:{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

#!git clone https://github.com/"owner"/"repository".git for public repositories

Changed directory to: /content/MSSP607-GitHub/MSSP607-GitHub

In [10]:
#a. We will look at stock data from Facebook, Apple, Amazon, Netflix, and Google from different files.  We will combine them into a single file and store the dataframe for further analysis.
#b. Read each file into a dataframe
df_aapl = pd.read_csv("data/Week 05 Examples/aapl.csv")
df_amzn = pd.read_csv("data/Week 05 Examples/amzn.csv")
df_fb = pd.read_csv("data/Week 05 Examples/fb.csv")
df_goog = pd.read_csv("data/Week 05 Examples/goog.csv")
df_nflx = pd.read_csv("data/Week 05 Examples/nflx.csv")

In [11]:
#c. Add a column to each dataframe, called 'ticker', indicating the ticker symbol it is for (Apple's is AAPL). This symbol is how you will look up a stock.  Each file name is the ticker symbol.
df_aapl["ticker"] = "AAPL"
df_amzn["ticker"] = "AMZN"
df_fb["ticker"] = "FB"
df_goog["ticker"] = "GOOG"
df_nflx["ticker"] = "NFLX"

In [12]:
#d. Append each file together into a single dataframe.
combined = pd.concat([df_aapl,df_amzn, df_fb, df_goog, df_nflx], ignore_index=True)
combined["ticker"].value_counts()

#e. Save the results in a CSV file called 'faanf.csv'.
combined.to_csv("faanf.csv",index=False)

In [13]:
#'fanng.csv', use type conversion to change the 'date' column into a 'datetime' and the 'volume' column into integers.  Then sort by 'date' and 'ticker.'
df_faanf = pd.read_csv("/content/MSSP607-GitHub/faanf.csv")
df_faanf["date"] = pd.to_datetime(df_faanf["date"])
df_faanf["volume"] = df_faanf["volume"].astype("int64")
df_faanf["volume"].dtype

dtype('int64')

In [14]:
df_sorted_faanf = df_faanf.sort_values(by=["date", "volume"])
df_sorted_faanf

           date    open    high     low   close    volume ticker
753  2018-01-02 1048.34 1066.94 1045.23 1065.00   1237564   GOOG
251  2018-01-02 1172.00 1190.00 1170.51 1189.01   2694494   AMZN
1004 2018-01-02  196.10  201.65  195.42  201.07  10966889   NFLX
502  2018-01-02  177.68  181.58  177.55  181.42  18151903     FB
0    2018-01-02  166.93  169.03  166.04  168.99  25555934   AAPL
...         ...     ...     ...     ...     ...       ...    ...
1003 2018-12-31 1050.96 1052.70 1023.59 1035.61   1493722   GOOG
501  2018-12-31 1510.80 1520.76 1487.00 1501.97   6954507   AMZN
1254 2018-12-31  260.16  270.10  260.00  267.66  13508920   NFLX
752  2018-12-31  134.45  134.64  129.95  131.09  24625308     FB
250  2018-12-31  157.85  158.68  155.81  157.07  35003466   AAPL

[1255 rows x 7 columns]

In [15]:
#g. Find the seven rows within the highest value for volume.
top7_rows = df_sorted_faanf.nlargest(n=7, columns="volume")
top7_rows

          date   open   high    low  close     volume ticker
644 2018-07-26 174.89 180.13 173.75 176.26  169803668     FB
555 2018-03-20 167.47 170.20 161.95 168.15  129851768     FB
559 2018-03-26 160.82 161.10 149.02 160.06  126116634     FB
556 2018-03-21 164.80 173.40 163.30 169.39  106598834     FB
182 2018-09-21 219.07 219.65 215.61 215.98   96246748   AAPL
245 2018-12-21 156.19 157.48 148.99 150.09   95744384   AAPL
212 2018-11-02 207.93 212.00 203.84 205.88   91328654   AAPL

In [16]:
#h. Use the melt() method to make the 'date' and 'ticker' key identifiers.  Melt the remaining columns so that there are not separated.
df_melt = df_faanf.melt(id_vars=["date","ticker" ], var_name="measurement", value_name="value")
df_melt

           date ticker measurement       value
0    2018-01-02   AAPL        open      166.93
1    2018-01-03   AAPL        open      169.25
2    2018-01-04   AAPL        open      169.26
3    2018-01-05   AAPL        open      170.14
4    2018-01-08   AAPL        open      171.04
...         ...    ...         ...         ...
6270 2018-12-24   NFLX      volume  9547616.00
6271 2018-12-26   NFLX      volume 14402735.00
6272 2018-12-27   NFLX      volume 12235217.00
6273 2018-12-28   NFLX      volume 10987286.00
6274 2018-12-31   NFLX      volume 13508920.00

[6275 rows x 4 columns]